name = "the-card-match"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "CACHE_KV"
id = "f020f616225a424395af267b463d6b71"
[vars]
VITE_SUPABASE_URL = https://lextybuzodixtpbmgjah.supabase.co
VITE_SUPABASE_ANON_KEY = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxleHR5YnV6b2RpeHRwYm1namFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY5ODM3NTMsImV4cCI6MjA5MjU1OTc1M30.rFBDIy7RIHOOJ17nb47veqinBVb7tnheWz-dJl473h4